export {
  EmbeddingService,
  buildEmbeddingServiceConfig,
  createTextBatches,
  buildEmbeddingCacheKey,
  estimateTextsTokenCount,
  readEmbeddingCache,
  writeEmbeddingCache,
  detectSpecializedTerms,
  findEmbeddingModelByPath,
  getRecommendedEmbeddingModel,
  calculateCosineSimilarity,
  compareEmbeddingModelResults,
  generateModelRecommendation,
  tryFallbackEmbeddingModels,
  type EmbeddingAnalysisRequest,
  type EmbeddingAnalysisResponse,
  type EmbeddingAnalysisResultItem,
  type EmbeddingCacheEntry,
  type EmbeddingServiceConfig,
} from './embedding-service/index';
export { default } from './embedding-service/index';
